services:
  main-container:
    build:
      context: .
      dockerfile: ./Dockerfile.external-test
      target: '${DOCKER_BUILD_TARGET:-default}'
    volumes:
      - ./src:/external-test-vite4-react18-swc/src
    ports:
      - 4173:4173
      - 5173:5173
