# syntax=docker/dockerfile:1

# Local packages must be Yalc'd into this directory BEFORE building this image
# (via ../../scripts/update-external-tests.sh)

FROM node:20.8.1-bullseye-slim AS base-environment
WORKDIR /app-vite4-react18-swc
RUN corepack enable

FROM base-environment AS base-deps

COPY package.json pnpm-lock.yam[l]  ./
COPY .yalc  .yalc/
RUN pnpm install

FROM base-deps AS base-app

COPY . ./
# We need to reapply the lockfile from deps, in case it changed
COPY --from=base-deps /app-vite4-react18-swc/pnpm-lock.yaml ./
RUN pnpm run clean

# 4173 = Vite preview
EXPOSE 4173
# 5173 = Vite dev
EXPOSE 5173


# A target for each check or test case. These are just for readability.
#   'run-all' = all project checks
#   'run-ci'  = all project checks, but for CI
#   'run-dev' = spin up a local dev server

FROM base-app AS run-all
CMD ["pnpm", "run", "all"]

FROM base-app AS run-ci
CMD ["pnpm", "run", "all:ci"]

FROM base-app AS run-dev
CMD ["pnpm", "run", "dev"]


FROM run-all AS default
LABEL external-test-name="vite4-react18-swc"
LABEL external-test.artifact.1="/app-vite4-react18-swc/pnpm-lock.yaml"
LABEL external-test.artifact.2="/app-vite4-react18-swc/coverage"
