services:
  cra5-react18:
    profiles: ["cra5-react18"]
    build:
      context: ./external-tests/cra5-react18
      dockerfile: Dockerfile.external-test
      target: ${DOCKER_BUILD_TARGET:-default}
    working_dir: /app-cra5-react18
    ports:
      - "3000:3000"
    volumes:
      - ./external-tests/cra5-react18/src:/app-cra5-react18/src:ro
    init: true
