version: "3.9"

services:
  cra5-react18:
    profiles: ["cra5-react18"]
    container_name: cra5-react18-container
    build:
      context: ./external-tests/cra5-react18
      dockerfile: Dockerfile.external-test
      target: ${DOCKER_BUILD_TARGET:-default}
    working_dir: /app-cra5-react18
    expose:
      - "3000"
    volumes:
      - ./external-tests/cra5-react18/src:/app-cra5-react18/src:ro
    init: true
