# General settings
engineStrict: true
linkWorkspacePackages: true
packageManagerStrictVersion: true
strictDepBuilds: true
verifyDepsBeforeRun: error

onlyBuiltDependencies:
- "@biomejs/biome"
- "esbuild"
ignoredBuiltDependencies:
- "core-js"
- "core-js-pure"
- "unrs-resolver"

# Workspace

packages:
  - packages/*
  - demos/*
  - docs-website

catalog:
  react: 19.1.1
  react-dom: 19.1.1
  typescript: 5.9.2
  # For libraries/packages:
  '@arethetypeswrong/cli': 0.18.2
  '@size-limit/esbuild': 11.2.0
  '@size-limit/esbuild-why': 11.2.0
  '@size-limit/file': 11.2.0
  '@types/react': 19.1.10
  '@types/react-dom': 19.1.7
  publint: 0.3.12
  size-limit: 11.2.0
  source-map-explorer: 2.5.3
  tsup: 8.5.0
  # For demo apps:
  # @TODO

# Named catalogs are looser
catalogs:
  react16:
    '@types/react': ^16.9.0
    '@types/react-dom': ^16.9.0
    react: ^16.9.0
    react-dom: ^16.9.0
  react17:
    '@types/react': ^17.0.0
    '@types/react-dom': ^17.0.0
    react: ^17.0.2
    react-dom: ^17.0.2
  react18:
    '@types/react': ^18.0.0
    '@types/react-dom': ^18.0.0
    react: ^18.2.0
    react-dom: ^18.2.0
  react19:
    '@types/react': ^19.1.8
    '@types/react-dom': ^19.1.6
    react: ^19.1.0
    react-dom: ^19.1.0
  typescriptLTS:
    # https://github.com/DefinitelyTyped/DefinitelyTyped#support-window
    typescript: 5.2.x
