# syntax=docker/dockerfile:1

# Local packages must be Yalc'd into this directory BEFORE building this image
# (via ../../scripts/update-external-tests.sh)

ARG NODE_VERSION=26

FROM node:${NODE_VERSION}-bullseye-slim AS base-environment
WORKDIR /app-node26-pnpm-cjs
# This external-test uses native pnpm, not Corepack
RUN npm install -g pnpm

FROM base-environment AS base-deps

COPY package.json pnpm-lock.yam[l]  ./
COPY .yalc  .yalc/
RUN pnpm install

FROM base-deps AS base-app

COPY . ./
# We need to reapply the lockfile from deps, in case it changed
COPY --from=base-deps /app-node26-pnpm-cjs/pnpm-lock.yaml ./


# A target for each check or test case. These are just for readability.
#   'run-all' = all project checks
#   'run-ci'  = all project checks, but for CI

FROM base-app AS run-all
CMD ["bash", "./external-test-checks.sh"]

FROM base-app AS run-ci
CMD ["bash", "./external-test-checks.sh"]


FROM run-all AS default
LABEL external-test-name="node26-pnpm-cjs"
LABEL external-test.artifact.1="/app-node26-pnpm-cjs/pnpm-lock.yaml"
