# syntax=docker/dockerfile:1

# Local packages must be Yalc'd into this directory BEFORE building this image
# (via ../../scripts/setup-framework-tests.sh)

FROM node:16.20.2-bullseye-slim as base-workspace
WORKDIR /framework-test-cra4-react16
RUN corepack enable

# 'base' is deps + project source
FROM base-workspace as base-deps

COPY package.json yarn.lock  ./
COPY .yalc  .yalc/
RUN yarn install

FROM base-workspace as base

# deps come second so that we don't lose any lockfile changes
COPY . ./
COPY --from=base-deps /framework-test-cra4-react16 /framework-test-cra4-react16/
RUN yarn run clean

# 3000 = React-Scripts dev server
EXPOSE 3000


# A target for each check or test case. These are just for readability.
#   'run-all' = all project checks
#   'run-ci'  = all project checks, but for CI
#   'run-dev' = spin up a local dev server

FROM base as run-all
CMD yarn run all

FROM base as run-ci
CMD yarn run all:ci

FROM base as run-dev
CMD yarn run start


FROM run-all as default
LABEL framework-test-name="cra4-react16"
