# For sanity and performance, local packages must be Yalc'd into this directory BEFORE
# building this image (via ../../scripts/setup-framework-tests.sh)

ARG NODE_VERSION=14

# 'base' is deps + project source: plain files only, without any checks or test cases
FROM node:${NODE_VERSION}-buster-slim as base

WORKDIR /framework-test-cra4-react16
COPY package.json yarn.lock  ./
COPY .yalc  .yalc/

RUN yarn install

COPY .env* *.cjs *.html *.js *.json *.mjs *.ts  ./
COPY public public/
COPY src src/

# 3000 = react-scripts start
EXPOSE 3000


# A target for each check or test case. These are just for readability.
#   'run-all'     = all project checks
#   'run-ci'      = all project checks, but for CI
#   'run-server'  = spin up a local dev server

FROM base as run-all
CMD yarn run all

FROM base as run-ci
CMD yarn run all:ci

FROM base as run-server
CMD yarn run start


FROM run-all as default
