version: '3.8'
services:
  main-container:
    build:
      context: .
      dockerfile: ./Dockerfile.framework-test
      target: '${DOCKER_BUILD_TARGET:-default}'
    volumes:
      - ./src:/framework-test-node18-cjs/src
    # no ports
