# syntax=docker/dockerfile:1

# Local packages must be Yalc'd into this directory BEFORE building this image
# (via ../../scripts/update-external-tests.sh)

FROM node:16.20.2-bullseye-slim as base-environment
WORKDIR /app-cra4-react16
RUN corepack enable

FROM base-environment as base-deps

COPY package.json yarn.loc[k]  ./
COPY .yalc  .yalc/
RUN yarn install

FROM base-deps as base-app

COPY . ./
# We need to reapply the lockfile from deps, in case it changed
COPY --from=base-deps /app-cra4-react16/yarn.lock ./
RUN yarn run clean

# 3000 = React-Scripts dev server
EXPOSE 3000


# A target for each check or test case. These are just for readability.
#   'run-all' = all project checks
#   'run-ci'  = all project checks, but for CI
#   'run-dev' = spin up a local dev server

FROM base-app as run-all
CMD yarn run all

FROM base-app as run-ci
CMD yarn run all:ci

FROM base-app as run-dev
CMD yarn run start


FROM run-all as default
LABEL external-test-name="cra4-react16"
LABEL external-test.artifact.1="/app-cra4-react16/yarn.lock"
LABEL external-test.artifact.2="/app-cra4-react16/coverage"
