version: '3.8'
services:
  main-container:
    build:
      context: .
      dockerfile: ./Dockerfile.external-test
      target: '${DOCKER_BUILD_TARGET:-default}'
    volumes:
      - ./src:/external-test-node22-cjs/src
    # no ports
