# syntax=docker/dockerfile:1

# Local packages must be Yalc'd into this directory BEFORE building this image
# (via ../../scripts/update-external-tests.sh)

ARG NODE_VERSION=20

FROM node:${NODE_VERSION}-bullseye-slim AS base-environment
WORKDIR /app-node20-cjs
# This external-test uses the bundled version of npm

FROM base-environment AS base-deps

COPY package.json package-lock.jso[n]  ./
COPY .yalc  .yalc/
RUN npm install

FROM base-deps AS base-app

COPY . ./
# We need to reapply the lockfile from deps, in case it changed
COPY --from=base-deps /app-node20-cjs/package-lock.json ./


# A target for each check or test case. These are just for readability.
#   'run-all' = all project checks
#   'run-ci'  = all project checks, but for CI

FROM base-app AS run-all
CMD ["bash", "./external-test-checks.sh"]

FROM base-app AS run-ci
CMD ["bash", "./external-test-checks.sh"]


FROM run-all AS default
LABEL external-test-name="node20-cjs"
LABEL external-test.artifact.1="/app-node20-cjs/package-lock.json"
