# syntax=docker/dockerfile:1

# Local packages must be Yalc'd into this directory BEFORE building this image
# (via ../../scripts/update-external-tests.sh)

ARG NODE_VERSION=20

FROM node:${NODE_VERSION}-bullseye-slim as base-workspace
WORKDIR /external-test-node20-cjs
RUN corepack enable


# 'base' is deps + project source
FROM base-workspace as base-deps

COPY package.json  ./
COPY .yalc  .yalc/
RUN npm install

FROM base-workspace as base

# deps come second so that we don't lose any lockfile changes
COPY . ./
COPY --from=base-deps /external-test-node20-cjs /external-test-node20-cjs/
RUN npm run clean


# A target for each check or test case. These are just for readability.
#   'run-all' = all project checks
#   'run-ci'  = all project checks, but for CI

FROM base as run-all
CMD npm run external-test

FROM base as run-ci
CMD npm run external-test:ci


FROM run-all as default
LABEL external-test-name="node20-cjs"
