# syntax=docker/dockerfile:1

# Local packages must be Yalc'd into this directory BEFORE building this image
# (via ../../scripts/update-external-tests.sh)

FROM node:18.19.0-bullseye-slim as base-workspace
WORKDIR /external-test-cra5-react18
RUN corepack enable

# 'base' is deps + project source
FROM base-workspace as base-deps

COPY package.json pnpm-lock.yam[l]  ./
COPY .yalc  .yalc/
RUN pnpm install

FROM base-workspace as base

# deps come second so that we don't lose any lockfile changes
COPY . ./
COPY --from=base-deps /external-test-cra5-react18 /external-test-cra5-react18/
RUN pnpm run clean

# 3000 = React-Scripts dev server
EXPOSE 3000


# A target for each check or test case. These are just for readability.
#   'run-all' = all project checks
#   'run-ci'  = all project checks, but for CI
#   'run-dev' = spin up a local dev server

FROM base as run-all
CMD pnpm run all

FROM base as run-ci
CMD pnpm run all:ci

FROM base as run-dev
CMD pnpm run start


FROM run-all as default
LABEL external-test-name="cra5-react18"
