services:
  main-container:
    build:
      context: .
      dockerfile: ./Dockerfile.external-test
      target: '${DOCKER_BUILD_TARGET:-default}'
    volumes:
      - ./src:/external-test-cra5-react18/src
    ports:
      - 3000:3000
