# syntax=docker/dockerfile:1

# Local packages must be Yalc'd into this directory BEFORE building this image
# (via ../../scripts/update-external-tests.sh)

FROM mcr.microsoft.com/playwright:v1.40.0-jammy AS base-environment
WORKDIR /app-nextjs13-playwright
RUN corepack enable

FROM base-environment AS base-deps

COPY package.json pnpm-lock.yam[l]  ./
COPY .yalc  .yalc/
RUN pnpm install

FROM base-deps AS base-app

COPY . ./
# We need to reapply the lockfile from deps, in case it changed
COPY --from=base-deps /app-nextjs13-playwright/pnpm-lock.yaml ./
RUN pnpm run clean

# 3000 = NextJS dev and start
EXPOSE 3000


# A target for each check or test case. These are just for readability.
#   'run-all'   = all project checks
#   'run-ci'    = all project checks, but for CI
#   'run-dev'   = spin up a local dev server
#   'run-prod'  = spin up a local server in production mode

FROM base-app AS run-all
CMD ["pnpm", "run", "all"]

FROM base-app AS run-ci
CMD ["pnpm", "run", "all:ci"]

FROM base-app AS run-dev
CMD ["pnpm", "run", "server:dev"]

FROM base-app AS run-prod
CMD pnpm run build && pnpm run server:prod


FROM run-all AS default
LABEL external-test-name="nextjs13-playwright"
LABEL external-test.artifact.1="/app-nextjs13-playwright/pnpm-lock.yaml"
LABEL external-test.artifact.2="/app-nextjs13-playwright/playwright-report"
LABEL external-test.artifact.2="/app-nextjs13-playwright/e2e-test-output"
