# syntax=docker/dockerfile:1

# Local packages must be Yalc'd into this directory BEFORE building this image
# (via ../../scripts/update-external-tests.sh)

ARG BUN_VERSION=1

FROM oven/bun:${BUN_VERSION} AS base-environment
WORKDIR /app-bun-vite5

FROM base-environment AS base-deps

COPY package.json bun.lock[b]  ./
COPY .yalc  .yalc/
RUN bun install

FROM base-deps AS base-app

COPY . ./
# We need to reapply the lockfile from deps, in case it changed
COPY --from=base-deps /app-bun-vite5/bun.lockb ./
RUN bun run clean

# 4173 = Vite preview
EXPOSE 4173
# 5173 = Vite dev
EXPOSE 5173


# A target for each check or test case. These are just for readability.
#   'run-all' = all project checks
#   'run-ci'  = all project checks, but for CI
#   'run-dev' = spin up a local dev server

FROM base-app AS run-all
CMD ["bun", "run", "all"]

FROM base-app AS run-ci
CMD ["bun", "run", "all:ci"]

FROM base-app AS run-dev
CMD ["bun", "run", "dev"]


FROM run-all AS default

LABEL external-test-name="bun-vite5"
LABEL external-test.artifact.1="/app-bun-vite5/bun.lockb"
