# syntax=docker/dockerfile:1

# Local packages must be Yalc'd into this directory BEFORE building this image
# (via ../../scripts/setup-framework-tests.sh)

FROM oven/bun:1.0.22 as base-workspace
WORKDIR /framework-test-bun-vite5

# 'base' is deps + project source
FROM base-workspace as base-deps

COPY package.json bun.lockb  ./
COPY .yalc  .yalc/
RUN bun install

FROM base-workspace as base

# deps come second so that we don't lose any lockfile changes
COPY . ./
COPY --from=base-deps /framework-test-bun-vite5 /framework-test-bun-vite5/
RUN bun run clean

# 4173 = Vite preview
EXPOSE 4173
# 5173 = Vite dev
EXPOSE 5173


# A target for each check or test case. These are just for readability.
#   'run-all' = all project checks
#   'run-ci'  = all project checks, but for CI
#   'run-dev' = spin up a local dev server

FROM base as run-all
CMD bun run all

FROM base as run-ci
CMD bun run all:ci

FROM base as run-dev
CMD bun run dev


FROM run-all as default
LABEL framework-test-name="bun-vite5"
