version: '3.8'
services:
  main-container:
    build:
      context: .
      dockerfile: ./Dockerfile.framework-test
      target: '${DOCKER_BUILD_TARGET:-default}'
    volumes:
      - ./src:/framework-test-bun-vite5/src
    ports:
      - 4173:4173
      - 5173:5173
