# syntax=docker/dockerfile:1

# For sanity and performance, local packages must be Yalc'd into this directory BEFORE
# building this image (via ../../scripts/setup-framework-tests.sh)

ARG BUN_VERSION=1

# 'base' is deps + project source: raw files only
FROM oven/bun:${BUN_VERSION} as base

WORKDIR /framework-test-bun-vite5
COPY bun.lockb package.json  ./
COPY .yalc  .yalc/

RUN bun install

COPY . ./

# 4173 = Vite preview
EXPOSE 4173
# 5173 = Vite dev
EXPOSE 5173


# A target for each check or test case. These are just for readability.
#   'run-all'     = all project checks
#   'run-ci'      = all project checks, but for CI
#   'run-server'  = spin up a local dev server

FROM base as run-all
CMD bun run all

FROM base as run-ci
CMD bun run all:ci

FROM base as run-server
CMD bun run dev


FROM run-all as default
LABEL framework-test-name="bun-vite5"
