# syntax=docker/dockerfile:1

# Local packages must be Yalc'd into this directory BEFORE building this image
# (via ../../scripts/update-external-tests.sh)

FROM denoland/deno:alpine-1.46.3 AS base-environment
WORKDIR /app-deno-fresh

# @TODO: Need some good versioning

FROM base-environment AS base-deps

# @TODO

FROM base-deps AS base-app

# @TODO

# 8000 = Fresh dev server
EXPOSE 8000


# A target for each check or test case. These are just for readability.
#   'run-all' = all project checks
#   'run-ci'  = all project checks, but for CI
#   'run-dev' = spin up a local dev server

FROM base-app AS run-all
CMD ["echo", "TODO: deno-fresh external test"]

FROM base-app AS run-ci
CMD ["echo", "TODO: deno-fresh external test"]

FROM base-app AS run-dev
CMD ["echo", "TODO: deno-fresh external test"]


FROM run-all AS default

LABEL external-test.name="deno-fresh"
