# syntax=docker/dockerfile:1

# Local packages must be Yalc'd into this directory BEFORE building this image
# (via ../../scripts/update-external-tests.sh)

FROM denoland/deno:alpine-1.46.3 as base-environment
WORKDIR /app-deno-fresh

# @TODO: Need some good versioning

FROM base-environment as base-deps

# @TODO

FROM base-deps as base-app

# @TODO

# 8000 = Fresh dev server
EXPOSE 8000


# A target for each check or test case. These are just for readability.
#   'run-all' = all project checks
#   'run-ci'  = all project checks, but for CI
#   'run-dev' = spin up a local dev server

FROM base-app as run-all
CMD echo "TODO: deno-fresh external test"

FROM base-app as run-ci
CMD echo "TODO: deno-fresh external test"

FROM base-app as run-dev
CMD echo "TODO: deno-fresh external test"


FROM run-all as default

LABEL external-test.name="deno-fresh"
