# syntax=docker/dockerfile:1

# Local packages must be Yalc'd into this directory BEFORE building this image
# (via ../../scripts/update-external-tests.sh)

ARG NODE_VERSION=18

FROM node:${NODE_VERSION}-bullseye-slim as base-environment
WORKDIR /app-node18-esm
RUN corepack enable

FROM base-environment as base-deps

COPY package.json package-lock.jso[n]  ./
COPY .yalc  .yalc/
RUN npm install

FROM base-deps as base-app

COPY . ./
# We need to reapply the lockfile from deps, in case it changed
COPY --from=base-deps /app-node18-esm/package-lock.json ./
RUN npm run clean


# A target for each check or test case. These are just for readability.
#   'run-all' = all project checks
#   'run-ci'  = all project checks, but for CI

FROM base-app as run-all
CMD npm run external-test

FROM base-app as run-ci
CMD npm run external-test:ci


FROM run-all as default
LABEL external-test-name="node18-esm"
LABEL external-test.artifact.1="/app-node18-esm/package-lock.json"
