version: '3.8'
services:
  main-container:
    build:
      context: .
      dockerfile: ./Dockerfile.framework-test
      target: '${DOCKER_BUILD_TARGET:-default}'
    volumes:
      - ./src:/framework-test-nextjs13-playwright/src
    ports:
      - 3000:3000
