name: Publish Release

on: workflow_dispatch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  publish-npm:
    name: Publish to NPM
    runs-on: ubuntu-latest
    # Only run for the original repo, and only the default branch, and only if it's properly protected
    if: |
      (! github.event.push.head.repo.fork)
        && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        && github.ref_protected == true
    strategy:
      matrix:
        package-name: [basic-library-template, react-library-template ]
    permissions:
      contents: read # Required to clone the repository when this template is used in a private repo.
      id-token: write # Required for npm trusted publishing via GitHub OIDC.
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: ./.github/reusable-workflows/setup-repo
        with:
          node-version: nvmrc
          enable-package-manager-cache: false

      - name: Publish to NPM
        run: |
          cd packages/${{ matrix.package-name }}
          pnpm pack --out package-${{ matrix.package-name }}-%v.tgz
          npm publish  --provenance --tag next  package-${{ matrix.package-name }}*.tgz

      - name: Verify published provenance
        run: |
          mkdir verify-publish
          cd verify-publish
          npm init -y
          npm install ${{ matrix.package-name }}@next
          npm audit signatures --json --include-attestations
